import test from "node:test";
import assert from "node:assert/strict";
import { addUnit, deleteUnits, freeKey, matchesRarity, references, selectFiltered, serializeJson, toggleSelection, TYPES, validateBundle } from "../work/test-dist/lib/editor-core.js";

function sample() { return { player:{playerName:"Gustavo",level:1,experience:0,zel:0,gems:0,karma:0,unitDex:["10011"]}, inventory:{nextKey:2,playerUnits:{"1":{unitId:"10011",type:0,currentLevel:1,currentExperience:0,currentBBLevel:1,currentSBBLevel:1,hpLevelUpBonus:0,atkLevelUpBonus:0,defLevelUpBonus:0,recLevelUpBonus:0,hpImpBonus:0,atkImpBonus:0,defImpBonus:0,recImpBonus:0}}}, parties:{parties:{"0":{slots:{"0":"1"},leaderUnitIndex:0}}} }; }

test("adds duplicate unit IDs without overwriting inventory records",()=>{const b=sample();const key=addUnit(b,{unitId:10011,unitName:"Fencer Vargas",maxLevel:150},{type:1,maxLevel:true,maxBB:true});assert.equal(key,"2");assert.equal(b.inventory.playerUnits["2"].currentLevel,150);assert.equal(b.inventory.playerUnits["2"].currentBBLevel,10);assert.deepEqual(b.player.unitDex,["10011"]);assert.equal(b.inventory.nextKey,3)});
test("freeKey skips occupied keys",()=>{const b=sample();b.inventory.playerUnits["2"]={...b.inventory.playerUnits["1"]};assert.equal(freeKey(b),3)});
test("reports party references before bulk deletion",()=>{const b=sample();assert.deepEqual(references(b,"1"),["party 0, slot 0"]);assert.deepEqual(deleteUnits(b,["1"]),["1: party 0, slot 0"]);assert.ok(validateBundle(b).some(x=>x.includes("does not exist")))});
test("validates malformed saves and preserves UTF-8 JSON",()=>{const b=sample();b.inventory.nextKey=1;b.player.unitDex.push("10011");const errors=validateBundle(b);assert.ok(errors.some(x=>x.startsWith("nextKey")));assert.ok(errors.some(x=>x.includes("duplicates")));assert.equal(JSON.parse(serializeJson({name:"Lico²"})).name,"Lico²")});
test("checkbox selection toggles multiple units without replacing previous choices",()=>{let selected=toggleSelection([],"5",true);selected=toggleSelection(selected,"6",true);assert.deepEqual(selected,["5","6"]);selected=toggleSelection(selected,"5",true);assert.deepEqual(selected,["6"]);assert.deepEqual(toggleSelection(selected,"9",false),["9"])});
test("selects all filtered rows without losing an existing selection",()=>{assert.deepEqual(selectFiltered(["9"],["2","5","9"]),["9","2","5"]);assert.deepEqual(selectFiltered([],[]),[])});
test("rarity filter accepts raw and labelled select values",()=>{assert.equal(matchesRarity(5,"5"),true);assert.equal(matchesRarity(5,"5 estrelas"),true);assert.equal(matchesRarity(4,"5"),false);assert.equal(matchesRarity(undefined,"5"),false);assert.equal(matchesRarity(undefined,"Todos"),true)});
test("Rex is the highest unit type ID and remains save-valid",()=>{assert.equal(TYPES[5],"Rex");const b=sample();b.inventory.playerUnits["1"].type=5;assert.deepEqual(validateBundle(b),[]);assert.throws(()=>addUnit(b,{unitId:10012},{type:6}),/between 0 and 5/)});
test("an empty party may use leaderUnitIndex zero to represent no leader",()=>{const b=sample();b.parties={nextKey:1,parties:{"0":{leaderUnitIndex:0,slots:{}}}};assert.deepEqual(validateBundle(b),[]);assert.equal(serializeJson(b.parties),'{\n  "nextKey": 1,\n  "parties": {\n    "0": {\n      "leaderUnitIndex": 0,\n      "slots": {}\n    }\n  }\n}\n')});
test("a non-empty party still rejects a leader index without a matching slot",()=>{const b=sample();b.parties.parties["0"].leaderUnitIndex=4;assert.match(validateBundle(b).join("\n"),/party 0: invalid leaderUnitIndex/)});
