import test from "node:test";
import assert from "node:assert/strict";
import { addUnit, deleteUnits, formatRarity, freeKey, inventorySelectionState, matchesRarity, moveInventoryBlock, normalizeInventoryKeys, organizeInventory, paginate, references, selectFiltered, serializeJson, toggleContiguousInventorySelection, toggleSelection, TYPES, validateBundle } from "../work/test-dist/lib/editor-core.js";

function sample() { return { player:{playerName:"Gustavo",level:1,experience:0,zel:0,gems:0,karma:0,unitDex:["10011"]}, inventory:{nextKey:2,playerUnits:{"1":{unitId:"10011",type:0,currentLevel:1,currentExperience:0,currentBBLevel:1,currentSBBLevel:1,hpLevelUpBonus:0,atkLevelUpBonus:0,defLevelUpBonus:0,recLevelUpBonus:0,hpImpBonus:0,atkImpBonus:0,defImpBonus:0,recImpBonus:0}}}, parties:{parties:{"0":{slots:{"0":"1"},leaderUnitIndex:0}}} }; }

test("adds duplicate unit IDs without overwriting inventory records",()=>{const b=sample();const key=addUnit(b,{unitId:10011,unitName:"Fencer Vargas",maxLevel:150},{type:1,maxLevel:true,maxBB:true});assert.equal(key,"2");assert.equal(b.inventory.playerUnits["2"].currentLevel,150);assert.equal(b.inventory.playerUnits["2"].currentBBLevel,10);assert.deepEqual(b.player.unitDex,["10011"]);assert.equal(b.inventory.nextKey,3)});
test("freeKey skips occupied keys",()=>{const b=sample();b.inventory.playerUnits["2"]={...b.inventory.playerUnits["1"]};assert.equal(freeKey(b),3)});
test("reports party references before bulk deletion",()=>{const b=sample();assert.deepEqual(references(b,"1"),["party 0, slot 0"]);assert.deepEqual(deleteUnits(b,["1"]),["1: party 0, slot 0"]);assert.ok(validateBundle(b).some(x=>x.includes("does not exist")))});
test("validates malformed saves and preserves UTF-8 JSON",()=>{const b=sample();b.inventory.nextKey=1;b.player.unitDex.push("10011");const errors=validateBundle(b);assert.ok(errors.some(x=>x.startsWith("nextKey")));assert.ok(errors.some(x=>x.includes("duplicates")));assert.equal(JSON.parse(serializeJson({name:"Lico²"})).name,"Lico²")});
test("checkbox selection toggles multiple units without replacing previous choices",()=>{let selected=toggleSelection([],"5",true);selected=toggleSelection(selected,"6",true);assert.deepEqual(selected,["5","6"]);selected=toggleSelection(selected,"5",true);assert.deepEqual(selected,["6"]);assert.deepEqual(toggleSelection(selected,"9",false),["9"])});
test("selects all filtered rows without losing an existing selection",()=>{assert.deepEqual(selectFiltered(["9"],["2","5","9"]),["9","2","5"]);assert.deepEqual(selectFiltered([],[]),[])});
test("paginates catalogs in safe groups of 250 and clamps invalid pages",()=>{const units=Array.from({length:2069},(_,id)=>id);const first=paginate(units,1);const last=paginate(units,99);assert.equal(first.items.length,250);assert.deepEqual([first.page,first.totalPages,first.total],[1,9,2069]);assert.equal(last.page,9);assert.equal(last.items.length,69);assert.equal(last.items[0],2000)});
test("rarity filter accepts raw and labelled select values",()=>{assert.equal(matchesRarity(5,"5"),true);assert.equal(matchesRarity(5,"5 estrelas"),true);assert.equal(matchesRarity(4,"5"),false);assert.equal(matchesRarity(undefined,"5"),false);assert.equal(matchesRarity(undefined,"Todos"),true)});
test("rarity labels convert internal zero-based values to one through seven stars and Omni",()=>{assert.equal(formatRarity(0,"estrela","estrelas","Omni"),"1 estrela");assert.equal(formatRarity(6,"estrela","estrelas","Omni"),"7 estrelas");assert.equal(formatRarity(7,"estrela","estrelas","Omni"),"Omni");assert.equal(formatRarity(8,"estrela","estrelas","Omni"),"—")});
test("Rex is the highest unit type ID and remains save-valid",()=>{assert.equal(TYPES[5],"Rex");const b=sample();b.inventory.playerUnits["1"].type=5;assert.deepEqual(validateBundle(b),[]);assert.throws(()=>addUnit(b,{unitId:10012},{type:6}),/between 0 and 5/)});
test("an empty party may use leaderUnitIndex zero to represent no leader",()=>{const b=sample();b.parties={nextKey:1,parties:{"0":{leaderUnitIndex:0,slots:{}}}};assert.deepEqual(validateBundle(b),[]);assert.equal(serializeJson(b.parties),'{\n  "nextKey": 1,\n  "parties": {\n    "0": {\n      "leaderUnitIndex": 0,\n      "slots": {}\n    }\n  }\n}\n')});
test("a non-empty party still rejects a leader index without a matching slot",()=>{const b=sample();b.parties.parties["0"].leaderUnitIndex=4;assert.match(validateBundle(b).join("\n"),/party 0: invalid leaderUnitIndex/)});
test("normalizes inventory keys from zero and rewrites string and numeric party references",()=>{const b=sample();b.inventory.playerUnits={"9":{...b.inventory.playerUnits["1"],unitId:"9"},"3":{...b.inventory.playerUnits["1"],unitId:"3"}};b.inventory.nextKey=99;b.parties.parties={"0":{slots:{"0":"9","1":3},leaderUnitIndex:0}};assert.deepEqual(normalizeInventoryKeys(b),{changed:2,nextKey:2});assert.deepEqual(Object.keys(b.inventory.playerUnits),["0","1"]);assert.equal(b.inventory.playerUnits["0"].unitId,"3");assert.equal(b.inventory.playerUnits["1"].unitId,"9");assert.deepEqual(b.parties.parties["0"].slots,{"0":"1","1":0});assert.equal(b.inventory.nextKey,2);assert.deepEqual(validateBundle(b),[])});

function organizedSample(){const b=sample();const unit={...b.inventory.playerUnits["1"]};b.inventory.playerUnits={"10":{...unit,unitId:"100",type:2},"20":{...unit,unitId:"200",type:0},"30":{...unit,unitId:"300",type:1},"40":{...unit,unitId:"400",type:0}};b.inventory.nextKey=41;b.parties.parties={"0":{slots:{"0":"20","1":30},leaderUnitIndex:0}};return b}
const organizedInfo=new Map([[100,{unitId:100,elementName:"Water",rarity:3}],[200,{unitId:200,elementName:"Fire",rarity:1}],[300,{unitId:300,elementName:"Dark",rarity:0}],[400,{unitId:400,elementName:"Fire",rarity:7}]]);
test("organizes inventory stably by party presence, element, rarity and type while preserving key slots",()=>{const party=organizedSample();const partyResult=organizeInventory(party,"party",organizedInfo);assert.deepEqual(Object.values(party.inventory.playerUnits).map(unit=>unit.unitId),["200","300","100","400"]);assert.deepEqual(party.parties.parties["0"].slots,{"0":"10","1":20});assert.equal(party.inventory.nextKey,41);assert.equal(partyResult.changed,3);const element=organizedSample();organizeInventory(element,"element",organizedInfo);assert.deepEqual(Object.values(element.inventory.playerUnits).map(unit=>unit.unitId),["200","400","100","300"]);const rarity=organizedSample();organizeInventory(rarity,"rarity",organizedInfo);assert.deepEqual(Object.values(rarity.inventory.playerUnits).map(unit=>unit.unitId),["300","200","100","400"]);const type=organizedSample();organizeInventory(type,"type",organizedInfo);assert.deepEqual(Object.values(type.inventory.playerUnits).map(unit=>unit.unitId),["200","400","300","100"]);const unitId=organizedSample();organizeInventory(unitId,"unitId",organizedInfo);assert.deepEqual(Object.values(unitId.inventory.playerUnits).map(unit=>unit.unitId),["100","200","300","400"])});
test("moves adjacent selected units as one block and updates party references",()=>{const b=organizedSample();assert.deepEqual(inventorySelectionState(b,["20","30"]),{contiguous:true,first:1,last:2,canUp:true,canDown:true});const result=moveInventoryBlock(b,["20","30"],"up");assert.equal(result.moved,true);assert.deepEqual([result.mapping["20"],result.mapping["30"]],["10","20"]);assert.deepEqual(Object.values(b.inventory.playerUnits).map(unit=>unit.unitId),["200","300","100","400"]);assert.deepEqual(b.parties.parties["0"].slots,{"0":"10","1":20});assert.equal(b.inventory.nextKey,41);assert.throws(()=>moveInventoryBlock(organizedSample(),["10","30"],"up"),/must be adjacent/)});
test("inventory movement refuses the outer boundaries without mutating the save",()=>{const top=organizedSample();const before=structuredClone(top);assert.equal(moveInventoryBlock(top,["10","20"],"up").moved,false);assert.deepEqual(top,before);const bottom=organizedSample();assert.equal(moveInventoryBlock(bottom,["30","40"],"down").moved,false)});
test("combines organization criteria like a stable SQL ORDER BY",()=>{const b=organizedSample();organizeInventory(b,["party","element","rarity","type"],organizedInfo);assert.deepEqual(Object.values(b.inventory.playerUnits).map(unit=>unit.unitId),["200","300","400","100"]);assert.deepEqual(b.parties.parties["0"].slots,{"0":"10","1":20})});
test("supports independent ASC and DESC direction for every organization rule",()=>{const b=organizedSample();organizeInventory(b,[{criterion:"party",direction:"desc"},{criterion:"element",direction:"desc"},{criterion:"rarity",direction:"desc"},{criterion:"type",direction:"desc"}],organizedInfo);assert.deepEqual(Object.values(b.inventory.playerUnits).map(unit=>unit.unitId),["100","400","300","200"]);assert.deepEqual(b.parties.parties["0"].slots,{"0":"40","1":30})});
test("sorts unit IDs numerically in both directions without changing their values",()=>{const asc=organizedSample();organizeInventory(asc,{criterion:"unitId",direction:"asc"},organizedInfo);assert.deepEqual(Object.values(asc.inventory.playerUnits).map(unit=>unit.unitId),["100","200","300","400"]);const desc=organizedSample();organizeInventory(desc,{criterion:"unitId",direction:"desc"},organizedInfo);assert.deepEqual(Object.values(desc.inventory.playerUnits).map(unit=>unit.unitId),["400","300","200","100"]);assert.deepEqual(new Set(Object.values(desc.inventory.playerUnits).map(unit=>unit.unitId)),new Set(["100","200","300","400"]))});
test("selection always stays contiguous and keeps the larger side after a middle deselection",()=>{const keys=["0","1","2","3","4","5","6"];assert.deepEqual(toggleContiguousInventorySelection([],"2",keys),["2"]);assert.deepEqual(toggleContiguousInventorySelection(["2"],"5",keys),["2","3","4","5"]);assert.deepEqual(toggleContiguousInventorySelection(["1","2","3","4","5"],"2",keys),["3","4","5"]);assert.deepEqual(toggleContiguousInventorySelection(["1","2","3","4","5"],"4",keys),["1","2","3"]);assert.deepEqual(toggleContiguousInventorySelection(["1","2","3","4","5"],"3",keys),["1","2"]);assert.deepEqual(toggleContiguousInventorySelection(["1","2"],"1",keys),["2"])});
