import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("organize page starts neutral and supports optional ASC and DESC rules",async()=>{const page=await read("app/page.tsx");assert.match(page,/\[\'organize\',\'organize\'/);assert.match(page,/ORGANIZE_CRITERIA: InventorySortCriterion\[\] = \["party","element","rarity","type","unitId","level","exp","bb","sbb"\]/);assert.match(page,/Record<InventorySortCriterion,InventorySortDirection\|null>/);assert.match(page,/party:null,element:null,rarity:null,type:null,unitId:null,level:null,exp:null,bb:null,sbb:null/);assert.match(page,/current\[criterion\]===direction\?null:direction/);assert.match(page,/direction\?\[\{criterion,direction\}\]:\[\]/);assert.match(page,/if\(!rules\.length\)return/);assert.match(page,/!ORGANIZE_CRITERIA\.some\(criterion=>organizeDirections\[criterion\]\)/);assert.match(page,/setOrganizationDirection\(criterion,"asc"\)/);assert.match(page,/setOrganizationDirection\(criterion,"desc"\)/);assert.match(page,/organizeInventory\(draft,rules,infoById\)/);assert.match(page,/sortUnitId/);for(const label of ["sortLevel","sortExp","sortBb","sortSbb"])assert.match(page,new RegExp(label));assert.match(page,/onClick=\{applyOrganization\}/);const section=page.slice(page.indexOf("tab==='organize'"),page.indexOf("tab==='add'"));assert.doesNotMatch(section,/deleteSelected|selectFiltered|clearSelection|<select/);assert.match(section,/type="checkbox"/)});
test("arrow direction matches visual movement while active selection locks every outside row",async()=>{const page=await read("app/page.tsx");assert.match(page,/const noSelection=selectedOrganize\.length===0/);assert.match(page,/canMoveUp=noSelection\?singleState\.canUp:top&&organizeState\.canUp/);assert.match(page,/canMoveDown=noSelection\?singleState\.canDown:bottom&&organizeState\.canDown/);assert.match(page,/disabled=\{!canMoveUp\}[^↑]+moveOrganized\("up",noSelection\?\[key\]:selectedOrganize\)/);assert.match(page,/disabled=\{!canMoveDown\}[^↓]+moveOrganized\("down",noSelection\?\[key\]:selectedOrganize\)/)});
test("organize page explicitly keeps changes in memory until Save",async()=>{const [page,i18n]=await Promise.all([read("app/page.tsx"),read("lib/i18n.ts")]);const apply=page.slice(page.indexOf("function applyOrganization"),page.indexOf("const partyMap"));assert.doesNotMatch(apply,/saveBundle|studioApi|localStorage/);assert.match(apply,/setBundle\(draft\)/);assert.match(i18n,/Changes are only written when you click Save/);assert.match(i18n,/alterações só serão gravadas ao clicar em Salvar/)});
test("organize controls use a vertical header with all nine criteria in one row",async()=>{const css=await read("app/globals.css");assert.match(css,/\.panel-title:has\(\.organize-actions\)\{[^}]*flex-direction:column/);assert.match(css,/\.organize-actions\{display:grid;grid-template-columns:minmax\(0,1fr\)/);assert.match(css,/\.organize-criteria\{display:grid;grid-template-columns:repeat\(9,minmax\(115px,1fr\)\)/);assert.match(css,/\.organize-criteria\{[^}]*overflow-x:auto/);assert.doesNotMatch(css,/\.organize-criteria\{grid-template-columns:repeat\([23],/)});
