"use client";

import { useEffect, useMemo, useState } from "react";
import {
  addUnit, asInt, cloneBundle, deleteUnits, ELEMENTS, formatRarity, hasSbb, owned,
  matchesRarity, references, selectFiltered, toggleSelection, TYPES, UNIT_FIELDS, validateBundle,
  type JsonObject, type SaveBundle, type UnitInfo, type UnitRecord,
} from "@/lib/editor-core";
import { detectLocale, locales, translate, type Locale } from "@/lib/i18n";
import { getBrowserFileService } from "@/lib/browser-file-service";

type DirectoryInfo = { path: string; name: string };
type BackupInfo = { name: string; modifiedAt: string };
type LoadedSave = { directory: DirectoryInfo; bundle: SaveBundle };
interface LegacyStudioAPI {
  isElectron: boolean;
  getDefaultSavePath(): Promise<string>;
  selectSaveDirectory(): Promise<string | null>;
  loadSave(directory: string): Promise<LoadedSave>;
  saveBundle(directory: string, bundle: SaveBundle): Promise<{name:string;path:string}>;
  listBackups(directory: string): Promise<BackupInfo[]>;
  restoreBackup(directory: string, backupName: string): Promise<LoadedSave & {safety:{name:string;path:string}}>;
  openDirectory(directory: string): Promise<boolean>;
}
declare global { interface Window { legacyStudio?: LegacyStudioAPI } }
type Tab = "player" | "owned" | "add" | "party" | "backups";
const FIELD_LABELS: Record<string, string> = { type: "Tipo", currentLevel: "Nível", currentExperience: "Experiência", currentBBLevel: "Nível BB", currentSBBLevel: "Nível SBB", hpLevelUpBonus: "Bônus HP", atkLevelUpBonus: "Bônus ATK", defLevelUpBonus: "Bônus DEF", recLevelUpBonus: "Bônus REC", hpImpBonus: "Imp HP", atkImpBonus: "Imp ATK", defImpBonus: "Imp DEF", recImpBonus: "Imp REC" };
const PLAYER_FIELDS = [["playerName", "Nome"], ["level", "Nível"], ["experience", "Experiência"], ["zel", "Zel"], ["gems", "Gemas"], ["karma", "Karma"]] as const;

export default function Home() {
  const [locale,setLocaleState]=useState<Locale>("en");
  const t=(key:string,vars:Record<string,string|number>={})=>translate(locale,key,vars);
  const setLocale=(next:Locale)=>{setLocaleState(next);localStorage.setItem("legacy-studio-locale",next);document.documentElement.lang=next};
  const [tab, setTab] = useState<Tab>("player"); const [directory, setDirectory] = useState<DirectoryInfo | null>(null);
  const [bundle, setBundle] = useState<SaveBundle | null>(null); const [baseline, setBaseline] = useState<SaveBundle | null>(null);
  const [units, setUnits] = useState<UnitInfo[]>([]); const [fullUnits, setFullUnits] = useState<Map<number, UnitInfo>>(new Map());
  const [status, setStatus] = useState("Selecione a pasta do save para começar"); const [toast, setToast] = useState("");
  const [search, setSearch] = useState(""); const [element, setElement] = useState("Todos"); const [rarity, setRarity] = useState("Todos"); const [unitType, setUnitType] = useState("Todos");
  const [selectedOwned, setSelectedOwned] = useState<string[]>([]); const [edit, setEdit] = useState<Record<string,string>>({});
  const [showInternal, setShowInternal] = useState(false); const [idSearch, setIdSearch] = useState(""); const [selectedDb, setSelectedDb] = useState<number | null>(null);
  const [addOptions, setAddOptions] = useState({ type: 0, maxLevel: false, maxBB: false, maxSBB: false });
  const [partyKey, setPartyKey] = useState(""); const [backups, setBackups] = useState<BackupInfo[]>([]); const [selectedBackup, setSelectedBackup] = useState("");
  const dirty = Boolean(bundle && baseline && JSON.stringify(bundle) !== JSON.stringify(baseline));
  const studioApi = () => window.legacyStudio ?? getBrowserFileService();

  useEffect(()=>{setLocale(detectLocale(localStorage.getItem("legacy-studio-locale")||navigator.language))},[]);
  useEffect(() => { Promise.all([fetch("./data/units_database_simple.json").then(r=>r.json()), fetch("./data/units_database_full.json").then(r=>r.json())]).then(([simple, full]: UnitInfo[][]) => { setUnits(simple); setFullUnits(new Map(full.map(x => [Number(x.unitId), x]))); }).catch(() => setStatus(translate(detectLocale(navigator.language),"catalogFailed"))); }, []);
  useEffect(() => { const api=window.legacyStudio ?? getBrowserFileService(); const language=detectLocale(localStorage.getItem("legacy-studio-locale")||navigator.language); if(!api){setStatus(translate(language,"appRequired"));return;} if(!api.isElectron){setStatus(translate(language,"chooseStart"));return;} api.getDefaultSavePath().then(path=>api.loadSave(path)).then(applyLoaded).catch(()=>setStatus(translate(language,"defaultMissing"))); }, []);
  useEffect(() => { const before = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", before); return () => window.removeEventListener("beforeunload", before); }, [dirty]);
  const infoById = useMemo(() => new Map(units.map(u => [Number(u.unitId), u])), [units]);
  const nameOf = (id: unknown) => infoById.get(Number(id))?.unitName || `Unidade desconhecida ${String(id)}`;
  const mutate = (fn: (draft: SaveBundle) => void) => setBundle(old => { if (!old) return old; const draft = cloneBundle(old); fn(draft); return draft; });
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 3200); };

  function applyLoaded(result: LoadedSave) { const loaded=result.bundle; setDirectory(result.directory); setBundle(loaded); setBaseline(cloneBundle(loaded)); setSelectedOwned([]); setStatus(`${Object.keys(owned(loaded)).length} ${t("loaded")} ${result.directory.name}`); refreshBackups(result.directory); }
  async function refreshBackups(dir = directory) { const api=studioApi(); if (!dir || !api) return; setBackups(await api.listBackups(dir.path)); }
  async function loadDirectory(path: string) {
    try { const api=studioApi(); if(!api) throw new Error("File access is unavailable in this browser"); applyLoaded(await api.loadSave(path)); }
    catch (error) { notify(`${t("loadFailed")}: ${error instanceof Error ? error.message : String(error)}`); }
  }
  async function chooseDirectory() { const api=studioApi(); if (!api) { notify(t("browserUnsupported")); return; } try { const path=await api.selectSaveDirectory(); if(path) await loadDirectory(path); } catch (error) { if(error instanceof Error && error.name==="AbortError") return; notify(String(error)); } }
  async function save() { const api=studioApi(); if (!bundle || !directory || !api) return; const errors = validateBundle(bundle); if (errors.length) { notify(`${t("saveBlocked")}: ${errors[0]}${errors.length > 1 ? ` (+${errors.length-1})` : ""}`); return; } try { const backup = await api.saveBundle(directory.path,bundle); setBaseline(cloneBundle(bundle)); await refreshBackups(); setStatus(`${t("saved")}. Backup: ${backup.name}`); notify(t("savedSafe")); } catch (error) { notify(`${t("writeFailed")}: ${String(error)}`); } }
  async function restoreBackup() { const api=studioApi(); if (!directory || !selectedBackup || !api || !confirm(t("restoreQuestion",{name:selectedBackup}))) return; try { const result=await api.restoreBackup(directory.path,selectedBackup); applyLoaded(result); notify(t("restored",{name:result.safety.name})); } catch (error) { notify(`${t("restoreFailed")}: ${String(error)}`); } }

  const ownedRows = useMemo(() => bundle ? Object.entries(owned(bundle)).filter(([,u]) => { const info=infoById.get(Number(u.unitId)); const q=search.toLocaleLowerCase(); return (!q || nameOf(u.unitId).toLocaleLowerCase().includes(q) || String(u.unitId).includes(q)) && (element==="Todos" || info?.elementName===element) && matchesRarity(info?.rarity,rarity) && (unitType==="Todos" || TYPES[Number(u.type)]===unitType); }) : [], [bundle, infoById, search, element, rarity, unitType]);
  const filteredDb = useMemo(() => units.filter(u => { const q=search.toLocaleLowerCase(); return (showInternal || !(Number(u.unitId)<10000 || u.elementName==="Unknown" || !u.unitName?.trim() || u.rarity===0)) && (!q || u.unitName?.toLocaleLowerCase().includes(q)) && (!idSearch || String(u.unitId).includes(idSearch)) && (element==="Todos" || u.elementName===element) && matchesRarity(u.rarity,rarity); }), [units, search, idSearch, element, rarity, showInternal]);
  const selectedRecord = bundle && selectedOwned.length===1 ? owned(bundle)[selectedOwned[0]] : null;
  function selectOwned(key: string, multi: boolean) { setSelectedOwned(old => toggleSelection(old,key,multi)); const rec=bundle ? owned(bundle)[key] : null; if (rec && !multi) setEdit(Object.fromEntries(UNIT_FIELDS.map(f => [f, f==="type" ? String(rec[f]) : String(rec[f] ?? 0)]))); }
  function applyOwned() { if (!selectedRecord || selectedOwned.length!==1) return; try { mutate(d => { const rec=owned(d)[selectedOwned[0]]; UNIT_FIELDS.forEach(f => rec[f]=asInt(edit[f], f)); }); notify(t("applied")); } catch(e) { notify(String(e)); } }
  function removeSelected() { if (!bundle || !selectedOwned.length) return; const count=selectedOwned.length; const refs=selectedOwned.flatMap(k=>references(bundle,k)); if (!confirm(`${t("deleteQuestion",{count})}${refs.length ? `\n\n${t("refsWarning",{count:refs.length})}`:""}`)) return; mutate(d=>deleteUnits(d,selectedOwned)); setSelectedOwned([]); notify(t("deleted",{count})); }
  function addSelected(all=false) { const chosen=all ? filteredDb : filteredDb.filter(u=>u.unitId===selectedDb); if (!chosen.length) { notify(t("selectFirst")); return; } if (all && !confirm(t("addAllQuestion",{count:chosen.length}))) return; mutate(d => chosen.forEach(info => addUnit(d, fullUnits.get(Number(info.unitId)) || info, addOptions))); notify(t("added",{count:chosen.length})); }
  const partyMap = (bundle?.parties.parties || {}) as Record<string, JsonObject>; const partyKeys=Object.keys(partyMap); const activeParty=(partyMap[partyKey || partyKeys[0]] || {}) as JsonObject; const activeSlots=(activeParty.slots || {}) as Record<string, string|number>;
  function updatePartySlot(slot: string, value: string) { const key=partyKey || partyKeys[0]; mutate(d=>{ const party=(d.parties.parties as Record<string,JsonObject>)[key]; const old=party.slots as Record<string,unknown>; const valuesAreNumbers=typeof Object.values(old)[0]==="number"; if (!value) delete old[slot]; else old[slot]=valuesAreNumbers ? Number(value) : value; }); }

  return <main className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark">BF</div><div><h1>Legacy Save Studio</h1><p>{t("appSubtitle")}</p></div></div><div className="top-actions"><label className="language-select" title={t("language")}><span>🌐</span><select value={locale} onChange={e=>setLocale(e.target.value as Locale)}>{locales.map(code=><option key={code} value={code}>{code.toUpperCase()}</option>)}</select></label><span className={`save-state ${dirty?"dirty":""}`}><i />{dirty?t("unsaved"):t("saved")}</span><button className="ghost" onClick={()=>directory&&(!dirty||confirm(t("discard")))&&loadDirectory(directory.path)}>{t("reload")}</button><button className="primary" onClick={save} disabled={!bundle}>{t("save")}</button></div></header>
    <div className="workspace"><aside><button className="folder-button" onClick={chooseDirectory}><span>＋</span><div><b>{t("openFolder")}</b><small>{directory?.name || t("saveFiles")}</small></div></button><nav>{([['player','player','◎'],['owned','owned','♙'],['add','add','＋'],['party','parties','♜'],['backups','backups','↶']] as [Tab,string,string][]).map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id); if(id==='add'){setSearch('');setElement('Todos');setRarity('Todos');}}}><span>{icon}</span>{t(label)}{id==='owned'&&bundle?<em>{Object.keys(owned(bundle)).length}</em>:null}</button>)}</nav><div className="privacy"><b>{t("local")}</b><p>{t("privacy")}</p></div></aside>
      <section className="content">{!bundle ? <div className="empty"><div className="empty-icon">⌁</div><h2>{t("openTitle")}</h2><p>{t("openText")}</p><button className="primary large" onClick={chooseDirectory}>{t("selectFolder")}</button><div className="required">{t("required")}: <code>playerdata.json</code> <code>unitinventory.json</code> <code>parties.json</code></div></div> : <>
        {tab==='player'&&<Panel title={t("playerData")} subtitle={t("playerSubtitle")}><div className="player-grid">{PLAYER_FIELDS.map(([key])=><label key={key}><span>{t(key==='playerName'?'name':key)}</span><input value={String(bundle.player[key]??'')} onChange={e=>mutate(d=>{d.player[key]=key==='playerName'?e.target.value:Number(e.target.value)})}/></label>)}</div><div className="quick"><span>{t("shortcuts")}</span>{([['gems',999999],['zel',999999999],['karma',999999999],['level',999]] as const).map(([key,value])=><button key={key} onClick={()=>mutate(d=>{d.player[key]=value})}>{t("maximum")} {t(key)}</button>)}</div></Panel>}
        {tab==='owned'&&<Panel title={t("ownedTitle")} subtitle={`${ownedRows.length} ${t("of")} ${Object.keys(owned(bundle)).length} ${t("units")}`} actions={<Filters t={t} search={search} setSearch={setSearch} element={element} setElement={setElement} rarity={rarity} setRarity={setRarity} type={unitType} setType={setUnitType}/> }>
          <div className="table-wrap"><table><thead><tr><th></th><th>{t("key")}</th><th>{t("unit")}</th><th>{t("element")}</th><th>★</th><th>{t("type")}</th><th>{t("level")}</th><th>{t("exp")}</th><th>BB</th><th>SBB</th></tr></thead><tbody>{ownedRows.map(([key,u])=>{const info=infoById.get(Number(u.unitId));return <tr key={key} className={selectedOwned.includes(key)?'selected':''} onClick={e=>selectOwned(key,e.ctrlKey||e.metaKey)}><td><input type="checkbox" checked={selectedOwned.includes(key)} onClick={event=>event.stopPropagation()} onChange={()=>selectOwned(key,true)} aria-label={`${t("unit")} ${nameOf(u.unitId)}`}/></td><td><code>{key}</code></td><td><b>{nameOf(u.unitId)}</b><small>ID {u.unitId}</small></td><td><span className={`element e${info?.element||0}`}>{info?.elementName||'Unknown'}</span></td><td>{formatRarity(info?.rarity,t("star"),t("stars"),t("omni"))}</td><td>{TYPES[Number(u.type)]}</td><td>{u.currentLevel}</td><td>{u.currentExperience}</td><td>{u.currentBBLevel}</td><td>{u.currentSBBLevel}</td></tr>})}</tbody></table></div>
          <div className="editor"><div className="editor-head"><div><b>{selectedRecord?nameOf(selectedRecord.unitId):selectedOwned.length>1?`${selectedOwned.length} ${t("units")} ${t("selected")}`:t("selectUnit")}</b><small>{selectedRecord?`${t("key")} ${selectedOwned[0]} · ID ${selectedRecord.unitId}`:t("clickEdit")}</small></div><div className="selection-actions"><button disabled={!ownedRows.length} onClick={()=>setSelectedOwned(old=>selectFiltered(old,ownedRows.map(([key])=>key)))}>{t("selectFiltered")}</button><button disabled={!selectedOwned.length} onClick={()=>setSelectedOwned([])}>{t("clearSelection")}</button><button className="danger" disabled={!selectedOwned.length} onClick={removeSelected}>{t("deleteSelected")}</button></div></div>{selectedRecord&&<><div className="field-grid">{UNIT_FIELDS.map(f=><label key={f}><span>{FIELD_LABELS[f]}</span>{f==='type'?<select value={edit[f]||'0'} onChange={e=>setEdit({...edit,[f]:e.target.value})}>{TYPES.map((name,i)=><option value={i} key={name}>{name}</option>)}</select>:<input type="number" value={edit[f]||'0'} onChange={e=>setEdit({...edit,[f]:e.target.value})}/>}</label>)}</div><div className="tool-row"><button onClick={()=>setEdit({...edit,currentLevel:String(infoById.get(Number(selectedRecord.unitId))?.maxLevel||1)})}>{t("maxLevel")}</button><button onClick={()=>setEdit({...edit,currentBBLevel:'10'})}>{t("maxBB")}</button><button onClick={()=>hasSbb(fullUnits.get(Number(selectedRecord.unitId)))?setEdit({...edit,currentSBBLevel:'10'}):notify(t("notSbb"))}>{t("maxSBB")}</button><button onClick={()=>setEdit({...edit,currentExperience:'0'})}>{t("resetExp")}</button><button onClick={()=>setEdit({...edit,hpLevelUpBonus:'0',atkLevelUpBonus:'0',defLevelUpBonus:'0',recLevelUpBonus:'0'})}>{t("resetBonuses")}</button><button onClick={()=>setEdit({...edit,hpImpBonus:'0',atkImpBonus:'0',defImpBonus:'0',recImpBonus:'0'})}>{t("resetImps")}</button><button className="primary" onClick={applyOwned}>{t("applyFields")}</button></div></>}</div>
        </Panel>}
        {tab==='add'&&<Panel title={t("catalogTitle")} subtitle={`${filteredDb.length} ${t("found")}`} actions={<Filters t={t} search={search} setSearch={setSearch} element={element} setElement={setElement} rarity={rarity} setRarity={setRarity} idSearch={idSearch} setIdSearch={setIdSearch}/>}><label className="internal"><input type="checkbox" checked={showInternal} onChange={e=>setShowInternal(e.target.checked)}/> {t("showInternal")}</label><div className="table-wrap catalog"><table><thead><tr><th>ID</th><th>{t("unit")}</th><th>{t("number")}</th><th>{t("element")}</th><th>★</th><th>{t("maxLevel")}</th><th>{t("evolvesFrom")}</th><th>{t("evolvesTo")}</th></tr></thead><tbody>{filteredDb.map(u=><tr key={u.unitId} className={selectedDb===u.unitId?'selected':''} onClick={()=>setSelectedDb(u.unitId)}><td><code>{u.unitId}</code></td><td><b>{u.unitName}</b></td><td>{u.unitNumber}</td><td><span className={`element e${u.element||0}`}>{u.elementName}</span></td><td>{formatRarity(u.rarity,t("star"),t("stars"),t("omni"))}</td><td>{u.maxLevel}</td><td>{u.evoFrom||'—'}</td><td>{u.evoInto||'—'}</td></tr>)}</tbody></table></div><div className="add-bar"><label>{t("type")}<select value={addOptions.type} onChange={e=>setAddOptions({...addOptions,type:Number(e.target.value)})}>{TYPES.map((name,i)=><option value={i} key={name}>{name}</option>)}</select></label>{([['maxLevel','maxLevel'],['maxBB','maxBB'],['maxSBB','maxSBB']] as const).map(([key,label])=><label className="check" key={key}><input type="checkbox" checked={Boolean(addOptions[key])} onChange={e=>setAddOptions({...addOptions,[key]:e.target.checked})}/>{t(label)}</label>)}<div/><button onClick={()=>addSelected(true)}>{t("addFiltered")}</button><button className="primary" onClick={()=>addSelected(false)}>{t("addSelected")}</button></div></Panel>}
        {tab==='party'&&<Panel title={t("partyTitle")} subtitle={t("partySubtitle")}><div className="party-picker"><label>{t("party")}<select value={partyKey||partyKeys[0]} onChange={e=>setPartyKey(e.target.value)}>{partyKeys.map(k=><option key={k}>{k}</option>)}</select></label><label>{t("leader")}<select value={String(activeParty.leaderUnitIndex??0)} onChange={e=>mutate(d=>{((d.parties.parties as Record<string,JsonObject>)[partyKey||partyKeys[0]]).leaderUnitIndex=Number(e.target.value)})}>{[0,1,2,3,4].map(i=><option key={i}>{i}</option>)}</select></label></div><div className="slots">{[0,1,2,3,4].map(i=><div className="slot" key={i}><span>{i===Number(activeParty.leaderUnitIndex)?'★':'◇'}</span><div><b>{t("slot")} {i}</b><small>{i===Number(activeParty.leaderUnitIndex)?t("partyLeader"):t("partyUnit")}</small></div><select value={String(activeSlots[String(i)]??'')} onChange={e=>updatePartySlot(String(i),e.target.value)}><option value="">{t("emptySlot")}</option>{Object.entries(owned(bundle)).map(([key,u])=><option value={key} key={key}>{key} · {nameOf(u.unitId)} · {TYPES[Number(u.type)]} · {t("level")} {u.currentLevel}</option>)}</select></div>)}</div></Panel>}
        {tab==='backups'&&<Panel title={t("backups")} subtitle={t("backupSubtitle")}><div className="backup-layout"><div className="backup-list">{backups.length?backups.map(item=><button key={item.name} className={selectedBackup===item.name?'selected':''} onClick={()=>setSelectedBackup(item.name)}><span>▣</span><div><b>{item.name}</b><small>{new Date(item.modifiedAt).toLocaleString(locale)}</small></div></button>):<p>{t("noBackups")}</p>}</div><div className="restore-card"><div>↶</div><h3>{t("restore")}</h3><p>{t("restoreText")}</p><button className="primary" disabled={!selectedBackup} onClick={restoreBackup}>{t("restoreSelected")}</button>{directory&&window.legacyStudio&&<button className="open-folder" onClick={()=>window.legacyStudio?.openDirectory(directory.path)}>{t("openSaveFolder")}</button>}</div></div></Panel>}
      </>}</section></div><footer><span>{status}</span><span>{t("catalog")}: {units.length.toLocaleString(locale)} {t("units")} · {t("offline")}</span></footer>{toast&&<div className="toast">{toast}</div>}</main>;
}

function Panel({title,subtitle,actions,children}:{title:string;subtitle:string;actions?:React.ReactNode;children:React.ReactNode}) { return <div className="panel"><div className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{actions}</div>{children}</div>; }
function Filters(p:{t:(key:string,vars?:Record<string,string|number>)=>string;search:string;setSearch:(v:string)=>void;element:string;setElement:(v:string)=>void;rarity:string;setRarity:(v:string)=>void;type?:string;setType?:(v:string)=>void;idSearch?:string;setIdSearch?:(v:string)=>void}) { return <div className="filters"><input placeholder={p.t("searchName")} value={p.search} onChange={e=>p.setSearch(e.target.value)}/>{p.setIdSearch&&<input className="id-filter" placeholder="ID" value={p.idSearch} onChange={e=>p.setIdSearch!(e.target.value)}/>}<select value={p.element} onChange={e=>p.setElement(e.target.value)}><option value="Todos">{p.t("all")}</option>{ELEMENTS.map(x=><option value={x} key={x}>{x}</option>)}</select><select value={p.rarity} onChange={e=>p.setRarity(e.target.value)}><option value="Todos">{p.t("all")}</option>{['0','1','2','3','4','5','6','7'].map(x=><option value={x} key={x}>{formatRarity(x,p.t("star"),p.t("stars"),p.t("omni"))}</option>)}</select>{p.setType&&<select value={p.type} onChange={e=>p.setType!(e.target.value)}><option value="Todos">{p.t("all")}</option>{TYPES.map(x=><option value={x} key={x}>{x}</option>)}</select>}</div>; }
